Feature/way458 - fiveTran integration Lambda
MechanicalRock/wayfinder-control-plane pull request #11
Opened 2022-02-03 05:11 UTC by JMiocevich

2022-02-04 01:43 UTC, edn01 commented on infrastructure/fivetran-stack.yml
> +            AWS: arn:aws:iam::834469178297:root
Please check this with Tim about security implication of giving cross account permissions

2022-02-04 05:48 UTC, JMiocevich commented on infrastructure/fivetran-stack.yml
> +            AWS: arn:aws:iam::834469178297:root
@temyers

2022-02-04 06:47 UTC, temyers requested changes

2022-02-04 06:47 UTC, temyers commented on ci/scripts/build.sh
>  echo "TODO: Run build process here."
```suggestion
```

2022-02-04 06:47 UTC, temyers commented on ci/scripts/sandbox-deploy.sh
> +npm run build
```suggestion
./ci/scripts/build.sh
```

Let's keep a consistent CI structure

2022-02-04 06:47 UTC, temyers commented on infrastructure/fivetran-stack.yml
> +            AWS: arn:aws:iam::834469178297:root
@edn01 @JMiocevich 

Cross account roles are a standard access control mechanism - so long as they are controlled and least privilege.

`834469178297` is the FiveTran account ID?  

Add a comment to document what the account ID is to aid readability

General principles:
* For external / thirdparty used roles, ExternalId provides an additional security mechanism to control access (must be known by the entity performing the assume role - effectively a shared secret.
* Least privilege access is essential
* Use Single Responsibility Principle when using cross account roles - they shouldn't be used for any other purpose.

Further Reading:
* https://docs.aws.amazon.com/IAM/latest/UserGuide/tutorial_cross-account-with-roles.html
* https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_common-scenarios_aws-accounts.html

2022-02-04 06:47 UTC, temyers commented on infrastructure/fivetran-stack.yml
> +            AWS: arn:aws:iam::834469178297:root
@edn01 @JMiocevich I think the current design is inadequate - can you explain why, and provide a better alternative?  Suggest pairing or do individually and compare notes (this is a good learning opportunity).  Alternatively, tell me why my assumptions are wrong.

Some questions to help with your thinking.

Questions:
* What permissions does Fivetran require?  What does it need to do?
* What does the role allow Fivetran to do that it shouldn't?
* Are there any smells in the current implementation that point to something being 'a bit iffy'?
  * Why?  And therefore what does it suggest as a possible alternative?
* What uses the current `FiveTranRole`?
* What does the current policy allow the role to do?

2022-02-04 06:47 UTC, temyers commented on infrastructure/fivetran-stack.yml
> +              sts:ExternalId: hidden_scientific
Does this need to be extracted into a parameter? - Are we likely to use this template in other scenarios where it is necessary?

General FYI (incase anyone was concerned) - this is *not* a secret for us (it is a secret for Fivetran to protect access control into our account) and the externalId will be visible in the generated role template.

2022-02-04 06:47 UTC, temyers commented on infrastructure/fivetran-stack.yml
> +  FiveTranRoleOutput:
`FiveTranRoleArn` would be a more accurate name.  Is it currently used anywhere (and hence would need references to be updated)?

2022-02-04 06:47 UTC, temyers commented on src/aws/secretsClient.ts
> +import { SecretsManagerClient, GetSecretValueCommand } from '@aws-sdk/client-secrets-manager'
TODO - This needs to be in a common lib - but one for later.

2022-02-04 06:47 UTC, temyers commented on src/commands/fiveTranInterface.ts
> +export interface fiveTranRequest {
There isn't a type library available for this?

:thinking:

2022-02-04 06:47 UTC, temyers commented on src/commands/opsGenieCommands.ts
> +      priority: 'P5',
Does the priority need to be a parameter?

2022-02-04 06:47 UTC, temyers commented on src/commands/opsGenieCommands.ts
> +export async function createOpsGenieAlert(message: string, alias: string, apiKey: string, accountId: string) {
https://matheus.ro/2018/01/29/clean-code-avoid-many-arguments-functions/

Would this be better served with a parameter object?

param objects make it easier for the caller - ensuring named arguments.
Still useful to minimise the number of attributes in a param object where possible (general comment - N/A in this case)

2022-02-04 06:47 UTC, temyers commented on src/commands/opsGenieCommands.ts
> +      message: message,
```suggestion
      alias,
      message, 
```

improve readability

2022-02-04 06:47 UTC, temyers commented on src/commands/opsGenieCommands.ts
> +      alias: alias,
```suggestion
```

2022-02-04 06:47 UTC, temyers commented on src/commands/opsGenieCommands.ts
> +  }
Pull the common parameters up to re-use?

```suggestion
function authorizationHeaders(apiKey: string) {
  return {
    headers: {
      Authorization: `GenieKey ${apiKey}`
    }
  }
  
export async function getOpsGenieAlert(alias: string, apiKey: string) {
  const options = {
    ...authorizationHeaders(apiKey),
  }
```

They could then be referenced elsewhere

2022-02-04 06:47 UTC, temyers commented on src/fivetran/opsGenie/lambdaHandler.ts
> +  if(insertTransactions.length == 0){
```suggestion
  const hasData = insertTransactions.length > 0
  if(hasData){
```

Recommend reversing the logic to aid readability:
- Avoid double negative logic (confusing)
- Prefer affirmative statements (somthing is true) - easier to grok - reduces cognitive load.

2022-02-04 06:47 UTC, temyers commented on src/fivetran/opsGenie/lambdaHandler.ts
> +    state = '2015-01-01T01:00:00.0Z'
Why this?

at the least this probably requires an explanation / reference to something.

2022-02-04 06:47 UTC, temyers commented on webpack.config.js
> +/* eslint-disable no-undef */
TL;DR - presume this was copy/pasta from another repo, with the `awsSamPlugin` the only change?

2022-02-04 06:51 UTC, JMiocevich commented on infrastructure/fivetran-stack.yml
> +  FiveTranRoleOutput:
See exports below "FiveTranRoleARN"

2022-02-04 06:52 UTC, JMiocevich commented on infrastructure/fivetran-stack.yml
> +  FiveTranRoleOutput:
value is exported, and that value is referenced by wayfinder-slack-api/acceptancetestStack opsGenieTokenSecret KMS key, allowing token decryption for FiveTran Role

2022-02-04 06:54 UTC, JMiocevich commented on infrastructure/fivetran-stack.yml
> +              sts:ExternalId: hidden_scientific
It seems to be workspace specific, the value doesn't change per connector or account. Leon and I had the same values, for every connector it is the same value.

I dont see that this will be reused, the role only needs to be created once. Then if we need multiple lambda connectors, they can reference the same role

2022-02-04 06:57 UTC, temyers commented on infrastructure/fivetran-stack.yml
> +              sts:ExternalId: hidden_scientific
> I dont see that this will be reused, the role only needs to be created once. Then if we need multiple lambda connectors, they can reference the same role
How does that influence the design? (related to the comments above)

2022-02-04 07:14 UTC, JMiocevich commented on infrastructure/fivetran-stack.yml
> +            AWS: arn:aws:iam::834469178297:root
834469178297 is FiveTran Account ID, will add comment

FiveTran Role Requires lambda.InvokeFunction, this could be limited to the specific lambda rather than *
However we are still attaching it to a specific lambda.
I Added Logging writes to make debugging easier
I Added getSecrets to specific needed secret, decryption  rights are still needed, hence the fiveTranRoleARN export

The AssumeRolePolicyDocument is what is required by fiveTran, not confident in what this does.

Currently only the opsGenieIntegration Lambda uses the fiveTran role, in future any other Connection Lambdas would use this role.

Limitations/Smelly Problems: 
Current implentation does not pass a token in on the fiveTran side for verification. Hence if roleARN and lambda name was know, Data could be extracted by anyone. I didn't consider this before, Bad.

Allows Logging to *,  is that an issue?

No restriction on what lambda it can be assigned too.

2022-02-04 07:31 UTC, JMiocevich commented on src/commands/fiveTranInterface.ts
> +export interface fiveTranRequest {
Couldn't find one 
One i found was this https://github.com/fivetran/typescript-closure-tools/

2022-02-07 00:54 UTC, JMiocevich commented on infrastructure/fivetran-stack.yml
> +            AWS: arn:aws:iam::834469178297:root
Resolved Discussed Issues regarding lambda invoke rights by seperating thje roles., However I have had too explicitly define a seperate role for the lambda kms decryption, rather than it auto creating one. 

This is because I need to export the role ARN for kms key decryption, however I cannot find a way to retrieve the auto created role by SAM. It seems like we've done this in wayfinder-slack-api, however i cant replicate it to work. Must be missing something.

I would prefer have it autocreate, as it makes the code cleaner and easier too read.

2022-02-07 00:57 UTC, JMiocevich commented on ci/scripts/sandbox-deploy.sh
> +npm run build
in wayfinderbackend and wayfinder-slack-api it is 'npm run build'

Made this change to be in alignment with the other repos

2022-02-07 00:59 UTC, JMiocevich commented on src/fivetran/opsGenie/lambdaHandler.ts
> +    state = '2015-01-01T01:00:00.0Z'
Will refactor to make it more modular and clear,  will create a Documentation explaining the process

2022-02-07 05:28 UTC, temyers commented on infrastructure/fivetran-stack.yml
> +          Action: sts:AssumeRole
Should be able to remove this permission now?

The FiveTranRole should only be used by Fivetran

```suggestion
```

2022-02-08 09:36 UTC, JMiocevich commented on webpack.config.js
> +/* eslint-disable no-undef */
yes

2022-02-08 09:37 UTC, JMiocevich commented on infrastructure/fivetran-stack.yml
> +          Action: sts:AssumeRole
Yes, tested and removed

2022-02-08 09:41 UTC, JMiocevich commented on src/fivetran/opsGenie/lambdaHandler.ts
> +  if(insertTransactions.length == 0){
logic improved

2022-02-08 09:41 UTC, JMiocevich commented on src/fivetran/opsGenie/lambdaHandler.ts
> +    state = '2015-01-01T01:00:00.0Z'
Refactored

2022-02-09 02:45 UTC, temyers submitted a review, later dismissed

2022-02-09 02:45 UTC, temyers commented on README.md
> +fiveTranRole: "aws iam list-roles --query 'Roles[?contains(RoleName,`FiveTranRole`)==`true`].Arn'"
Minor.

This could be brittle to changes in the template/naming.  

I generally prefer to get this from the cloudformation stack outputs (does not need to be an exported), as it is explicit for exactly where the role is coming from.

Explicit vs implicit coupling.

2022-02-09 02:45 UTC, temyers commented on README.md
```suggestion
**NOTE**: The secret above is not a secret for us and can be hard coded.  See [`src/fivetran/lambdaOpsGenie/fiveTranSecret.ts`](./src/fivetran/lambdaOpsGenie/fiveTranSecret.ts) for further details
```

2022-02-09 02:45 UTC, temyers commented on src/fivetran/lambdaOpsGenie/fiveTranSecret.ts
> +export const secret: secrets = { fiveTranKey: '@IkB/B,Dk`ts{c-UN]48}#=oeoV9UR' }
```suggestion
// This is not a secret for us, so can be stored here in plain text.
// This is using the Fivetran secret field as a verification token - enabling us to verify that the call received is coming from our configured Fivetran integration
export const secret: secrets = { fiveTranKey: '@IkB/B,Dk`ts{c-UN]48}#=oeoV9UR' }
```

2022-02-09 02:48 UTC, JMiocevich commented on README.md
> +fiveTranRole: "aws iam list-roles --query 'Roles[?contains(RoleName,`FiveTranRole`)==`true`].Arn'"
Can have this as outputs, but this is completely for copy and paste into fiveTran, one time setup in fivetran

2022-02-09 02:49 UTC, JMiocevich commented on README.md
> +fiveTranRole: "aws iam list-roles --query 'Roles[?contains(RoleName,`FiveTranRole`)==`true`].Arn'"
will refactor

2022-02-09 03:03 UTC, temyers approved these changes

2022-02-09 03:03 UTC, merged